name: Release
on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
  GH_TOKEN: ${{ secrets.PAT_GITHUB }}

jobs:
  release-package:
    name: Release Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '18.12.0'

      - name: Write npmrc
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: .npmrc
          contents: |
            @shopuptech:registry=https://npm.pkg.github.com
            registry=https://registry.yarnpkg.com/
            //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
            always-auth=true
          write-mode: overwrite

      - name: Release Package
        run: |
          yarn 
          yarn release
