name: Release
on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}

jobs:
  release-package:
    name: Release Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '18.12.0'

      - name: Set Auth Token in Config
        run: yarn config set 'npmRegistries["//npm.pkg.github.com"].npmAuthToken' "${GITHUB_TOKEN}"

      - name: Create Release
        run: |
          yarn 
          yarn release
