name: Release
on:
  push:
    branches:
      - master
env:
  GH_TOKEN: ${{ secrets.PAT_GITHUB }}

jobs:
  release-package:
    name: Release Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '18.12.0'

      - name: Set NPM Config
        run: npm config set '//npm.pkg.github.com/:_authToken' "${GH_TOKEN}"

      - name: Create Release
        run: |
          yarn 
          yarn release

      - name: Publish Package
        run: |
          yarn publish --verbose
